version = '2'

[linters]
default = 'all'
disable = [
  'depguard',
  'exhaustive',
  'exhaustruct',
  'godox',
  'ireturn',
  'mnd',
  'musttag',
  'nlreturn',
  'sqlclosecheck',
  'wsl',
]
enable = ['wsl_v5']

[linters.settings]
[linters.settings.tagliatelle]
[linters.settings.tagliatelle.case]
[linters.settings.tagliatelle.case.rules]
json = 'camel'

[linters.settings.varnamelen]
ignore-names = ['rx', 'tx', 'db', 'ok', 'mw', 'gw', 'rt', 'id']
ignore-decls = ['w http.ResponseWriter', 'r *http.Request', 'g *Gateway']

[linters.settings.wsl_v5]
allow-first-in-block = true
allow-whole-block = false
branch-max-lines = 2
disable = ['decl']

[linters.exclusions]
generated = 'lax'
presets = ['comments', 'common-false-positives', 'legacy', 'std-error-handling']
paths = ['third_party$', 'builtin$', 'examples$']

[[linters.exclusions.rules]]
linters = ['gosec']
text = 'G601:'

[[linters.exclusions.rules]]
linters = ['gochecknoglobals', 'gochecknoinits']
path = 'cmd/.*\.go'

[[linters.exclusions.rules]]
linters = ['err113', 'wrapcheck']
path = 'cmd/.*\.go'

[[linters.exclusions.rules]]
linters = ['revive']
path = 'internal/common/fs_operations.go'
text = 'avoid meaningless package names'

[severity]
default = 'warn'

[[severity.rules]]
linters = ['exhaustive', 'exhaustruct', 'godox']
severity = 'info'

[formatters]
enable = ['gci', 'gofumpt', 'goimports']

[formatters.exclusions]
generated = 'lax'
paths = ['third_party$', 'builtin$', 'examples$']
