# run with treefmt --allow-missing-formatter

[global]
excludes = [
  # txt files
  "**/*.txt",
  # gitignore
  "**/.gitignore",
  # go.sum & go.mod
  "go.sum",
  "go.mod",
  # vendor directory
  "vendor/**",
  # generated files
  "internal/pb/pb.pb.go",
  "python/labours/pb_pb2.py",
  "cmd/hercules/plugin_template_source.go",
]

### Misc

[formatter.prettier]
command = "prettier"
options = ["-w"]
includes = [
  "*.html",
  "*.css",
  "*.yaml",
  "*.yml",
  "*.js",
  "*.json",
  "*.md",
]

### Go

[formatter.gofumpt]
command = "gofumpt"
options = ["-w"]
includes = ["*.go"]

[formatter.gci]
command = "gci"
options = ["-w"]
includes = ["*.go"]
priority = 1        # run after gofumpt

### Shell

[formatter.shellcheck]
command = "shellcheck"
includes = ["*.sh"]

[formatter.shfmt]
command = "shfmt"
options = ["-s", "-w"]
includes = ["*.sh"]
priority = 1                            # run after shellcheck
